{{ strtoupper($appName) }} - DAILY SALES REPORT
{{ str_repeat('=', strlen($appName) + 23) }}

{{ $reportDate }}

Here's your end-of-day sales summary. Review the metrics below to track performance and identify trends.


PERFORMANCE SNAPSHOT
--------------------
Orders Placed:    {{ $totalOrders }}
Units Sold:       {{ $totalItemsSold }}
Total Revenue:    {{ $currencySymbol }}{{ number_format($totalRevenue, 2) }}

@if($productsSold->isEmpty())

NO SALES RECORDED
-----------------
There were no completed orders on this date.

Consider reviewing your traffic sources or promotional campaigns to identify opportunities for improvement.

@else
PRODUCT BREAKDOWN
-----------------
@foreach($productsSold as $product)
* {{ $product->product_name }}
  Units: {{ $product->total_quantity }} | Price: {{ $currencySymbol }}{{ number_format($product->unit_price, 2) }} | Subtotal: {{ $currencySymbol }}{{ number_format($product->total_revenue, 2) }}
@endforeach

@endif
--------------------
Automated report generated by {{ $appName }}.
Sent to store administrators daily at 8:00 PM.

{{ $appUrl }}
